### PR TITLE
Newsweek Clone Webpage

### PR DESCRIPTION
**Pull request by keneogu**
This project is about the cloning of the Newsweek webpage
We used
-bootstrap framework
-media queries

### CODE REVIEW

**Review by Georjane — CHANGES_REQUESTED** [review]
## Status: Changes Required 🔁 🚫 
### Hi Team @keneogu and @necmigunduz 🙌
Wow, your project looks really nice👍👍👌. It is an exact replica of the original website👏👏👏. You guys have done a great job with the clone.🎊
However, there are a few things I noticed:🚩🚩

- [x] Your project doesn't make good use of the bootstrap classes. The project specification emphasized the use of bootstrap, but I noticed you have a CSS file of almost 500lines of code. Making good use of bootstrap classes can greatly reduce these lines of code to less than half of what you are using right now.

bootstrap

- [x] Also, I would suggest you remove the list style type for the listed items which are supposed to be tag elements in the footer element

footer

- [x] For your media queries, that is after the breakpoint of 991px, your page breaks at a couple of points, including the navbar before it readjusts itself for larger screens. For example, see the screenshots below:

screen1
screen2

Please kindly implement the changes above and submit them for another code review. Feel free to reach out to me on slack, if you have any questions, **_Witah Georjane._**🤝🤝

Wish you the best in your project and Happy Coding!!💻

**Comment by necmigunduz** [comment]
We kindly request another code-review:
Things done: 
- Fixed the errors after the feedback

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

Hi @keneogu and @necmigunduz  

You've done a good job so far :+1:  but there's a little more to be done before this project can be approved. See below:
## REQUIRED
- [ ] On tablet screen, the **subscribe section** doesn't match that of the original page
**Original**
image
**Yours**
image
- [ ] The **newsletter section** should be fixed
**Original**
image
**Yours**
image
## Make the required changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by necmigunduz** [comment]
Fixed the error accordingly with the last feedback.
We would kindly request you to  make another review, and inform us if more revision is required or if none is required, to approve it ?

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:



_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Pull request merged**
